<a href="https://colab.research.google.com/github/nabila-zurain/First-Project/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Multiple Linear Regression
# When dependent variable(y) is affected by more than one independent variable
# Models the linear relationship between a single dependent continuous variable and more than one independent variable
# Import libraries

import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd

In [ ]:
# importing dataset
data_set = pd.read_csv('https://trello-attachments.s3.amazonaws.com/6062c6af283e86843a32b025/60d0152706cf05391bac797c/0ced7d9ccd720cb82d87e6ff95ee701c/Startups_Data.csv')
data_set.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
# Extracting independent and dependent variable
x = data_set.iloc[:,:-1].values # iloc = index location. -1 at the end means not include profit. 
# so it extract column: R&D Spend, Administration, Marketing Spend and State
# Another way you can do is data_set.iloc[:,:4] as dataframe.iloc[:,start_col:end_col] ---> result from start column and end column -1
y = data_set.iloc[:,4]
# only extract values from profit column

In [ ]:
x
# R&D Spend , Administration , Marketing Spend, State

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [ ]:
y
# Profit

0     192261.83
1     191792.06
2     191050.39
3     182901.99
4     166187.94
5     156991.12
6     156122.51
7     155752.60
8     152211.77
9     149759.96
10    146121.95
11    144259.40
12    141585.52
13    134307.35
14    132602.65
15    129917.04
16    126992.93
17    125370.37
18    124266.90
19    122776.86
20    118474.03
21    111313.02
22    110352.25
23    108733.99
24    108552.04
25    107404.34
26    105733.54
27    105008.31
28    103282.38
29    101004.64
30     99937.59
31     97483.56
32     97427.84
33     96778.92
34     96712.80
35     96479.51
36     90708.19
37     89949.14
38     81229.06
39     81005.76
40     78239.91
41     77798.83
42     71498.49
43     69758.98
44     65200.33
45     64926.08
46     49490.75
47     42559.73
48     35673.41
49     14681.40
Name: Profit, dtype: float64

In [ ]:
# Encoding Dummy Variables
# Use LabelEncoder class to convert categorical into numbers
# One Hot Encoder
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
# create object for the class
labelencoder_x = LabelEncoder() 
# replace the column after transformation # from independent variable you only pass index 3 (state column) only
x[:,3] = labelencoder_x.fit_transform(x[:,3]) 
x[:,3]

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0], dtype=object)

In [ ]:
transformer = ColumnTransformer(
    transformers = [
                    ("OneHot",  # just a name
                     OneHotEncoder(), # the transformer class
                     [3]) # the column to be applied on
    ],
    remainder = 'passthrough'   # passthrough means do not apply anything to the remaining column
)
x = transformer.fit_transform(x.tolist()) # give result in list
x = x.astype('int')

In [ ]:
x

# [california florida newYork  r&d     admin    marketing]
# [0          0        1       165349   136897  471784   ]

array([[     0,      0,      1, 165349, 136897, 471784],
       [     1,      0,      0, 162597, 151377, 443898],
       [     0,      1,      0, 153441, 101145, 407934],
       [     0,      0,      1, 144372, 118671, 383199],
       [     0,      1,      0, 142107,  91391, 366168],
       [     0,      0,      1, 131876,  99814, 362861],
       [     1,      0,      0, 134615, 147198, 127716],
       [     0,      1,      0, 130298, 145530, 323876],
       [     0,      0,      1, 120542, 148718, 311613],
       [     1,      0,      0, 123334, 108679, 304981],
       [     0,      1,      0, 101913, 110594, 229160],
       [     1,      0,      0, 100671,  91790, 249744],
       [     0,      1,      0,  93863, 127320, 249839],
       [     1,      0,      0,  91992, 135495, 252664],
       [     0,      1,      0, 119943, 156547, 256512],
       [     0,      0,      1, 114523, 122616, 261776],
       [     1,      0,      0,  78013, 121597, 264346],
       [     0,      0,      1,

In [ ]:
data_set.shape

(50, 5)

In [ ]:
# Split the dataset into training and test set

from sklearn.model_selection import train_test_split
# test_size = 0.2 means that 20% of the data is testing dataset
# and rest 80% of data is training dataset
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state=0 ) # will give 4 values at the end. 
# random_state=0 means it choose training and testing randomly 

In [ ]:
# fitting the MLR to the training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression() # create object
regressor.fit(x_train,y_train)

LinearRegression()

In [ ]:
# Predict the test set result
y_pred = regressor.predict(x_test)
y_pred

array([103015.24646785, 132581.94062687, 132448.09397396,  71975.74395634,
       178537.52007853, 116161.05196901,  67851.47761322,  98791.74112204,
       113969.41004647, 167921.22416079])

In [ ]:
y_test # actual values

28    103282.38
11    144259.40
10    146121.95
41     77798.83
2     191050.39
27    105008.31
38     81229.06
31     97483.56
22    110352.25
4     166187.94
Name: Profit, dtype: float64

In [ ]:
y_pred # predicted values

array([103015.24646785, 132581.94062687, 132448.09397396,  71975.74395634,
       178537.52007853, 116161.05196901,  67851.47761322,  98791.74112204,
       113969.41004647, 167921.22416079])

In [ ]:
# evaluate model performance 
from sklearn.metrics import r2_score
accuracy = r2_score(y_test, regressor.predict(x_test))
print('Accuracy: ',accuracy)

Accuracy:  0.9347065984136423


In [ ]:
# Predict profit

california = int(input('Are you from California enter 1 if yes alse 0: '))
florida = int(input('Are you from Florida enter 1 if yes alse 0: '))
newyork = int(input('Are you from NewYork enter 1 if yes alse 0: '))
r_d = int(input('Enter R&D spend: '))
admin = int(input('Enter administration spend: '))
market = int(input('Enter marketing spend: '))

data = {'california':california,'florida':florida,'newyork':newyork, # create dictionaries to make it easier to create dataframe
       'r_d':r_d,'admin':admin,'market':market}

user_input = pd.DataFrame(data,index=[0],columns=['california','florida','newyork', # must mention the column same as key in dictionaries
       'r_d','admin','market']) # create a dataframe to make it easier for prediction

predict_profit = regressor.predict(user_input) # apply model to make prediction
print("\nPredicted Profit of Startup is: ",predict_profit[0]) # Mr Yash: if not specify the row, it will give row 0 and 1. but i've checked still give [0] only

Are you from California enter 1 if yes alse 0: 1
Are you from Florida enter 1 if yes alse 0: 0
Are you from NewYork enter 1 if yes alse 0: 1
Enter R&D spend: 230
Enter administration spend: 356
Enter marketing spend: 123

Predicted Profit of Startup is:  43534.56914741471


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
